### ISSUE TITLE
Range issue on mp servers

### ISSUE THREAD

**Issue by GamertechAU** [Darkhax-Minecraft/MobStages#13]
MobStages-1.12.2-2.0.8

Currently using MobStages on a server and it works perfectly aside from one thing.

I've left ranges at default, so from your CF page it should be 256 but end-game gated mobs are still spawning around my base even when I'm 2k+ blocks away from it.

I'm using FTB for chunk claiming/chunk loading, so it might be that it's counting as 'me' and continuing to spawn gated mobs around my base as if I was there?

Main problem is I've got end-game mobs unlocked while other players aren't as far along and don't have the gear to survive them.

Any advice on this Darkhax?

**Comment by Darkhax** [comment]
It sounds like the mobs spawned in those chunks while you were there and have not de-spawned yet, probably because the chunks were kept loaded by chunk loading or the mob in question has properties which prevent despawning. This is mainly a technical limitation of intentional vanilla/modded mechanics.
